import { marked } from "marked"
import { useState, useEffect } from "react"

interface ProposalModalProps {
    content: string
    onClose: () => void
    isExisting: boolean
}

export default function ProposalModal({ content, onClose, isExisting }: ProposalModalProps) {
    const [copied, setCopied] = useState(false)
    const [htmlContent, setHtmlContent] = useState("")

    useEffect(() => {
        // Convert markdown to HTML when content changes
        const convert = async () => {
            const html = await marked(content)
            setHtmlContent(html)
        }
        convert()
    }, [content])

    const handleCopy = () => {
        navigator.clipboard.writeText(content)
        setCopied(true)
        setTimeout(() => setCopied(false), 2500)
    }

    return (
        <>
            <div
                className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm"
                onClick={onClose}
            >
                <div
                    className="card rounded-xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl"
                    onClick={e => e.stopPropagation()}
                >
                    <div className="flex items-center justify-between p-6 border-b border-theme">
                        <div>
                            <h2 className="text-primary font-bold text-lg">Proposal Draft</h2>
                            <p className="text-muted text-xs mt-0.5">
                                {isExisting ? "Previously generated draft" : "Freshly generated by Gemini AI"}
                            </p>
                        </div>
                        <button
                            onClick={onClose}
                            className="text-secondary w-8 h-8 rounded-lg flex items-center
                                       justify-center transition-all cursor-pointer"
                            style={{ border: "1px solid transparent" }}
                            onMouseEnter={e => {
                                e.currentTarget.style.backgroundColor = "var(--bg-card-hover)"
                                e.currentTarget.style.borderColor = "var(--border)"
                                e.currentTarget.style.color = "var(--text-primary)"
                            }}
                            onMouseLeave={e => {
                                e.currentTarget.style.backgroundColor = "transparent"
                                e.currentTarget.style.borderColor = "transparent"
                                e.currentTarget.style.color = "var(--text-secondary)"
                            }}
                        >
                            ✕
                        </button>
                    </div>

                    {/* Render as HTML instead of plain text */}
                    <div className="flex-1 overflow-y-auto p-6">
                        <div
                            className="tiptap text-secondary text-sm leading-relaxed"
                            dangerouslySetInnerHTML={{ __html: htmlContent }}
                            // dangerouslySetInnerHTML renders HTML string as actual HTML
                            // We use .tiptap class so our CSS styles apply here too
                        />
                    </div>

                    <div className="p-6 border-t border-theme flex items-center justify-between">
                        <span className="text-muted text-xs">
                            {content.length.toLocaleString()} characters
                        </span>
                        <button
                            onClick={handleCopy}
                            className="btn-outline-accent px-4 py-2 rounded text-sm font-medium cursor-pointer"
                        >
                            Copy to Clipboard
                        </button>
                    </div>
                </div>
            </div>

            {/* Toast */}
            <div
                className="fixed bottom-8 z-100 transition-all duration-300"
                style={{
                    left: "50%",
                    transform: copied
                        ? "translateX(-50%) translateY(0)"
                        : "translateX(-50%) translateY(80px)",
                    opacity: copied ? 1 : 0,
                    pointerEvents: "none",
                }}
            >
                <div
                    className="flex items-center gap-2 px-5 py-3 rounded-lg shadow-xl"
                    style={{
                        backgroundColor: "var(--bg-card)",
                        border: "1px solid var(--accent-border)",
                    }}
                >
                    <div className="w-5 h-5 rounded-full bg-emerald-500/20 border border-emerald-500/40
                                    flex items-center justify-center text-emerald-400 text-xs">
                        ✓
                    </div>
                    <span className="text-primary text-sm font-medium whitespace-nowrap">
                        Copied to clipboard
                    </span>
                </div>
            </div>
        </>
    )
}